// app/layout.tsx or _app.tsx (depending on your Next.js setup)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google"; // Google OAuth provider
import { Toaster } from "react-hot-toast"; // Toaster for toast notifications
import "./globals.css"; // Global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the application with GoogleOAuthProvider and Toaster */}
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>
          {/* Toaster component to show notifications */}
          <Toaster />
          {/* Render the children, which will be the pages of your app */}
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
